'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { test } = require('node:test');
const { LocalMusicLibrary, localFileId } = require('../desktop/local-music-library');
test('offline records survive; content relinking preserves IDs, playlists and media bytes', async t => {
  const temp = fs.mkdtempSync(path.join(os.tmpdir(), 'mineradio-relink-'));
  t.after(() => fs.rmSync(temp, { recursive: true, force: true }));
  const file = path.join(temp, 'song.mp3'), moved = path.join(temp, 'renamed.mp3'), copy = path.join(temp, 'copy.mp3');
  fs.writeFileSync(file, 'fixture-audio-bytes');
  fs.writeFileSync(path.join(temp, 'song.lrc'), '[00:01.000]原有旁挂歌词');
  const library = new LocalMusicLibrary({ userDataPath: temp, parseMetadata: async () => ({ common: { title: 'fixture' } }) });
  const first = await library.importFiles([file]); const track = first.tracks[0], token = library.mediaToken;
  fs.renameSync(file, moved);
  const index = fs.readFileSync(library.indexPath);
  assert.equal(library.listTracksSync().count, 0); assert.equal((await library.listTracks()).missing, 1);
  assert.deepEqual(fs.readFileSync(library.indexPath), index, 'offline enumeration cannot delete or change user records');
  assert.equal(library.resolveTrack(track.localFileId).localMissing, true);
  const relinked = await library.importFiles([moved]);
  assert.match(library.lyricForTrack(track.localFileId).lyric, /原有旁挂歌词/, 'moving audio alone cannot erase persisted lyrics');
  assert.equal(relinked.count, 1); assert.equal(relinked.tracks[0].localFileId, track.localFileId); assert.equal(library.mediaToken, token);
  fs.copyFileSync(moved, copy); assert.equal((await library.importFiles([copy])).count, 1, 'exact duplicate content is indexed once');
  fs.unlinkSync(copy);
  const reopened = new LocalMusicLibrary({ userDataPath: temp });
  assert.equal(reopened.listTracksSync().count, 1, 'available duplicate remains usable when the selected copy disappears');
  const response = await reopened.mediaResponse(new Request(track.localUrl)); assert.equal(await response.text(), 'fixture-audio-bytes');
  const different = path.join(temp, 'different.mp3'); fs.writeFileSync(different, 'fixture-audio-other');
  assert.equal((await library.importFiles([different])).count, 2, 'same size and metadata cannot collapse distinct content');
  fs.renameSync(moved, file); assert.equal(reopened.listTracksSync().count, 1, 'reattaching the original path restores its entry');
});
test('version 1 index and capability token remain readable without destructive migration', t => {
  const temp = fs.mkdtempSync(path.join(os.tmpdir(), 'mineradio-local-v1-'));
  t.after(() => fs.rmSync(temp, { recursive: true, force: true }));
  const file = path.join(temp, 'old.mp3'); fs.writeFileSync(file, 'old');
  const token = 'a'.repeat(48), id = localFileId(file);
  const original = JSON.stringify({ version: 1, mediaToken: token, records: [{ id, audioPath: file, name: 'legacy' }] });
  fs.writeFileSync(path.join(temp, 'local-music-library.json'), original);
  const library = new LocalMusicLibrary({ userDataPath: temp });
  assert.equal(library.listTracksSync().tracks[0].localFileId, id); assert.equal(library.mediaToken, token);
  assert.equal(fs.readFileSync(library.indexPath, 'utf8'), original);
});
