'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm');
const {loadFunctions}=require('./helpers/classic-functions');
function fixture(){let now=1000;const c=vm.createContext({Date:{now:()=>now},console:{warn(){}},Promise,Map,Number});loadFunctions(c,'public/js/modules/05-playback/07-search.js',['createPlaybackMetadataCache','resetPlaybackMetadataCaches','controlSourceProbeKey','controlSourceBlockedLabel','probeControlSourcePlayback']);loadFunctions(c,'public/js/modules/05-playback/18-cuefield-automix-integration.js',['cuefieldAutoMixAudioDescriptor']);c.controlSourceProbeCache=c.createPlaybackMetadataCache(90000);c.cuefieldAudioDescriptorCache=c.createPlaybackMetadataCache(240000);c.playbackQualityTrackKey=(s,p)=>p+':'+s.id;c.cuefieldSongKey=s=>s.id;c.songProviderKey=()=> 'qq';c.resolveAlbumGaplessPlaybackData=async()=>({url:'https://fixture.invalid/audio'});c.fetchBeatPrefetchAudioUrl=async s=>'https://fixture.invalid/'+s.id;return {c,advance:n=>now+=n};}
test('2000 source probes and descriptors stay bounded and keep valid hits',async()=>{const {c}=fixture();let probes=0,urls=0;c.resolveAlbumGaplessPlaybackData=async()=>{probes++;return {url:'https://fixture.invalid/a'};};c.fetchBeatPrefetchAudioUrl=async s=>{urls++;return 'https://fixture.invalid/'+s.id;};for(let i=0;i<2000;i++){await c.probeControlSourcePlayback({id:String(i)},'qq');await c.cuefieldAutoMixAudioDescriptor({id:String(i)});}for(const cache of [c.controlSourceProbeCache,c.cuefieldAudioDescriptorCache]){assert.equal(cache.stats().entries,64);assert(cache.stats().bytes<=256*1024);assert.equal(cache.stats().pending,0);}await c.probeControlSourcePlayback({id:'1999'},'qq');await c.cuefieldAutoMixAudioDescriptor({id:'1999'});assert.equal(probes,2000);assert.equal(urls,2000);assert.equal(c.cuefieldAudioDescriptorCache.get('0'),null);});
test('LRU hit changes eviction order; TTL expiry deletes retained data',async()=>{const {c,advance}=fixture(),cache=c.createPlaybackMetadataCache(100);for(let i=0;i<64;i++)await cache.load(String(i),()=>({value:i}));assert(cache.get('0'));await cache.load('new',()=>({value:1}));assert(cache.get('0'));assert.equal(cache.get('1'),null);advance(101);assert.equal(cache.stats().entries,0);assert.equal(cache.stats().bytes,0);});
test('same-key in-flight work shares a promise; reset retires late account results',async()=>{const {c}=fixture();let release,count=0;c.fetchBeatPrefetchAudioUrl=()=>{count++;return new Promise(r=>release=r);};const first=c.cuefieldAutoMixAudioDescriptor({id:'x'}),second=c.cuefieldAutoMixAudioDescriptor({id:'x'});await Promise.resolve();assert.equal(count,1);c.resetPlaybackMetadataCaches();release('https://fixture.invalid/old');assert.equal(await first,null);assert.equal(await second,null);assert.equal(c.cuefieldAudioDescriptorCache.stats().entries,0);});
test('failed source probes and URL requests are retryable, never cached',async()=>{const {c}=fixture();let n=0;c.resolveAlbumGaplessPlaybackData=async()=>{n++;throw Error('offline');};assert.equal((await c.probeControlSourcePlayback({id:'x'},'qq')).state,'unknown');await c.probeControlSourcePlayback({id:'x'},'qq');assert.equal(n,2);c.fetchBeatPrefetchAudioUrl=async()=>{throw Error('offline');};await assert.rejects(c.cuefieldAutoMixAudioDescriptor({id:'x'}));assert.equal(c.cuefieldAudioDescriptorCache.stats().entries,0);assert.equal(c.cuefieldAudioDescriptorCache.stats().pending,0);});
test('oversized URL/key is usable for its caller without entering retained cache',async()=>{const {c}=fixture();const url='https://fixture.invalid/'+ 'x'.repeat(20000);c.fetchBeatPrefetchAudioUrl=async()=>url;assert.equal((await c.cuefieldAutoMixAudioDescriptor({id:'large'})).proxyUrl,url);assert.equal(c.cuefieldAudioDescriptorCache.stats().entries,0);c.fetchBeatPrefetchAudioUrl=async()=> 'https://fixture.invalid/ok';await c.cuefieldAutoMixAudioDescriptor({id:'k'.repeat(4097)});assert.equal(c.cuefieldAudioDescriptorCache.stats().entries,0);});
test('pending ownership table is bounded even for 200 simultaneous unique callers',async()=>{const {c}=fixture(),cache=c.createPlaybackMetadataCache(1000),resolvers=[];const jobs=Array.from({length:200},(_,i)=>cache.load(String(i),()=>new Promise(r=>resolvers.push(r))));await Promise.resolve();assert.equal(cache.stats().pending,32);c.controlSourceProbeCache=cache;c.resetPlaybackMetadataCaches();resolvers.forEach(r=>r({ok:true}));assert((await Promise.all(jobs)).every(value=>value===null));assert.equal(cache.stats().pending,0);assert.equal(cache.stats().entries,0);});
test('newer same-key request survives a late pre-reset settlement',async()=>{const {c}=fixture(),cache=c.createPlaybackMetadataCache(1000);let oldRelease,newRelease;const old=cache.load('a',()=>new Promise(r=>oldRelease=r));await Promise.resolve();cache.clear();const fresh=cache.load('a',()=>new Promise(r=>newRelease=r));await Promise.resolve();oldRelease({value:'old'});assert.equal(await old,null);assert.equal(cache.stats().pending,1);newRelease({value:'new'});assert.equal((await fresh).value,'new');assert.equal(cache.get('a').value,'new');});

test('reset before the fetch microtask prevents old-account work from starting',async()=>{const {c}=fixture(),cache=c.createPlaybackMetadataCache(1000);let calls=0;const pending=cache.load('old',()=>{calls++;return {value:'old'};});cache.clear();assert.equal(await pending,null);assert.equal(calls,0);assert.equal(cache.stats().pending,0);});
